# Generated by Django 5.0.1 on 2024-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='img/announcement')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
