# Generated by Django 5.0.1 on 2024-05-24 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='img/announcement')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcements.header')),
            ],
            bases=('announcements.header',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcements.header')),
            ],
            bases=('announcements.header',),
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcements.header')),
            ],
            bases=('announcements.header',),
        ),
    ]
